"""
===============================================================================
BOOTSTRAP MEDIATION SHRINKAGE CONFIDENCE INTERVAL
===============================================================================

Purpose:
    Estimates a bootstrap confidence interval for the mediation shrinkage
    percentage for each dataset/model combination, using the retrieval analysis
    data produced by the main retrieval statistical pipeline.

Input:
    outputs/<RUN_NAME>/csv/retrievals_ranks.csv

    This file is generated by 4_main_retrieval_statistics.py and contains the
    long-format retrieval analysis data used as input to the bootstrap.

Workflow:
    1. Load retrievals_ranks.csv using pandas.read_csv().

    2. For each configured dataset and model, select only the corresponding
       rows from the retrieval data.

    3. Exclude the native/base resolution from the bootstrap analysis because
       native retrieval is a tautology: the query and gallery embeddings are
       identical by construction, giving Cosine_Sim = 1 and Top-1 = True for
       every image.

    4. Estimate the mediation shrinkage percentage and its bootstrap confidence
       interval using the custom bootstrap_shrinkage_ci() function imported
       from Funcs_retrieval_stats.py.

       bootstrap_shrinkage_ci():
           - Performs N_BOOT bootstrap draws (500 by default).
           - Fits the required GEE models for each bootstrap draw.
           - Uses seed=42 for reproducibility.
           - Returns the shrinkage percentage confidence interval and the number
             of successful bootstrap draws.

    5. Save the results for each dataset/model combination to
       mediation_shrinkage_bootstrap.csv using pandas.DataFrame.to_csv().

    6. Support interrupted runs:
       - Previously completed results are reloaded from the output CSV.
       - Individual bootstrap draws are saved to checkpoint files.
       - A combination is considered complete only when its checkpoint contains
         all N_BOOT attempted draws.
       - An interrupted run can therefore be resumed without restarting
         completed bootstrap draws.

Output:
    outputs/<RUN_NAME>/csv/mediation_shrinkage_bootstrap.csv

Checkpoint files:
    outputs/<RUN_NAME>/csv/bootstrap_checkpoints/
        <dataset>_<model>_draws.csv

Custom functions used:
    Funcs_retrieval_stats.py:
        bootstrap_shrinkage_ci()

    This script:
        save_results()
        combo_fully_done()

Public/external functions used:
    pandas.read_csv()
    pandas.DataFrame()
    DataFrame.to_csv()
    os.path.isfile()
    os.path.getsize()

Configuration:
    DATASETS and RUN_NAME are imported from config.py.
    Bootstrap iteration count is controlled by N_BOOT in this script.

===============================================================================
"""

import os
import warnings
import pandas as pd
from Funcs_retrieval_stats import bootstrap_shrinkage_ci
from config import DATASETS, RUN_NAME

warnings.filterwarnings("ignore")


def main():
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    run_dir = os.path.join(BASE_DIR, "outputs", RUN_NAME)
    csv_dir = os.path.join(run_dir, "csv")
    checkpoint_dir = os.path.join(csv_dir, "bootstrap_checkpoints")

    N_BOOT = 10  # bump up if you have time to spare; 2 GEE fits per draw per model-dataset

    ranks_file = os.path.join(csv_dir, "retrievals_ranks.csv")
    if not os.path.isfile(ranks_file):
        print(f"'{ranks_file}' not found. Run 4_main_retrieval_statistics.py first.")
        return

    ranks_all = pd.read_csv(ranks_file)
    model_names = ["ResNet18", "VGG16", "ViT"]

    output_path = os.path.join(csv_dir, "mediation_shrinkage_bootstrap.csv")

    # ------------------------------------------------------------
    # Resume support, combo level: reload whatever a previous
    # (possibly interrupted) run already finished and saved.
    # ------------------------------------------------------------
    results = {}
    if os.path.isfile(output_path):
        prev = pd.read_csv(output_path)
        for _, row in prev.iterrows():
            results[(row["Dataset"], row["Model"])] = row.to_dict()
        print(f"Found existing results for {len(results)} combination(s) in {output_path}.")

    def save_results():
        cols = ["Dataset", "Model", "Shrinkage_pct_CI_Lower", "Shrinkage_pct_CI_Upper", "Shrinkage_pct_n_boot_success"]
        df = pd.DataFrame(results.values())[cols]
        df.to_csv(output_path, index=False)

    def combo_fully_done(dataset_name, model_name):
        """A combo is fully done only if its checkpoint file shows all
        N_BOOT draws were attempted -- not just that a results row
        exists (that row could be stale from a run with a different
        N_BOOT)."""
        checkpoint_file = os.path.join(checkpoint_dir, f"{dataset_name}_{model_name}_draws.csv")
        if not os.path.isfile(checkpoint_file) or os.path.getsize(checkpoint_file) == 0:
            return False
        existing = pd.read_csv(checkpoint_file)
        if existing.empty:
            return False
        return int(existing["draw_index"].max()) + 1 >= N_BOOT

    try:
        for dataset_name, dataset_cfg in DATASETS.items():
            base_resolution = dataset_cfg["base_resolution"]

            for model_name in model_names:
                key = (dataset_name, model_name)

                if key in results and combo_fully_done(dataset_name, model_name):
                    print(f"Skipping {dataset_name}/{model_name} (already complete: {N_BOOT}/{N_BOOT} draws).")
                    continue

                print("=" * 60)
                print(f"BOOTSTRAP: {dataset_name} / {model_name}")
                print("=" * 60)

                subset = ranks_all[
                    (ranks_all["Dataset"] == dataset_name) & (ranks_all["Model"] == model_name)
                ].copy()

                if subset.empty:
                    print(f"Skipping '{dataset_name}/{model_name}' (no rows).")
                    continue

                # Same exclusion as the main inferential pipeline: native
                # resolution is a tautology (Cosine_Sim = 1, Top1 = True for
                # every image), not a real observation.
                inferential_df = subset[subset["Resolution"] != base_resolution].copy()

                checkpoint_file = os.path.join(checkpoint_dir, f"{dataset_name}_{model_name}_draws.csv")

                ci_result = bootstrap_shrinkage_ci(
                    inferential_df, n_boot=N_BOOT, seed=42,
                    checkpoint_file=checkpoint_file,
                    progress_label=f"{dataset_name}/{model_name}",
                )
                ci_result["Dataset"] = dataset_name
                ci_result["Model"] = model_name

                results[key] = ci_result

                # Save the instant a combo finishes, so a crash between
                # combos never loses ones that are already done.
                save_results()
                print(f"Saved progress: {output_path}")

    except KeyboardInterrupt:
        print("\nStopped early.")
        print(f"Completed combinations are saved in: {output_path}")
        print(f"The in-progress combination's draws are saved in: {checkpoint_dir}")
        print("Just re-run this script to resume from here.")
        return

    if not results:
        print("[NO DATA] mediation_shrinkage_bootstrap.csv")
        return

    print("=" * 60), print("BOOTSTRAP SHRINKAGE CI COMPLETE"), print("=" * 60)


if __name__ == "__main__":
    main()