"""
===============================================================================
COSINE SIMILARITY STATISTICAL ANALYSIS
===============================================================================

Purpose:
    Performs descriptive and cross-model inferential statistical analyses on
    the cosine-similarity measurements generated for each dataset, model, and
    image resolution.

Input:
    outputs/<RUN_NAME>/csv/<dataset>_cosine.csv

    These files are generated by the cosine metric generation script and contain
    the pairwise cosine similarity between each image's base-resolution
    embedding and its embedding at each configured resolution.

Workflow:
    1. Load each dataset's cosine-similarity CSV using pandas.read_csv().

    2. Compute descriptive cosine-similarity statistics across all models and
       resolutions using the custom compute_similarity_stats() function
       imported from Funcs_stats.py.

    3. Exclude the native/base resolution from inferential analyses because
       each embedding is compared with itself at that resolution, producing
       Cosine_Sim = 1.0 for every image. The native resolution is therefore
       retained for descriptive statistics but excluded from ANOVA, normality,
       and post-hoc tests.

    4. Validate the dataset structure and required resolution columns using
       the custom validate_dataset() function from Funcs_stats.py.

    5. Convert the wide-format cosine-similarity table into long format using
       the custom reshape_to_long() function from Funcs_stats.py. The resulting
       table contains the image/model/resolution observations required for
       repeated-measures analysis.

    6. Perform a two-way repeated-measures ANOVA using the custom
       run_two_way_rm_anova() function from Funcs_stats.py to test the effects
       of model and resolution, as well as their interaction, on Cosine_Sim.

    7. Check normality of paired differences between repeated measurements
       using the custom check_paired_diff_normality() function from
       Funcs_stats.py.

    8. Check normality of the repeated-measures ANOVA residuals using the custom
       check_anova_residual_normality() function from Funcs_stats.py.

    9. Perform post-hoc comparisons following the ANOVA using the custom
       run_posthoc_tests() function from Funcs_stats.py.

   10. Combine the statistical results from all datasets using pandas.concat()
       and save each result table as a separate CSV using
       DataFrame.to_csv().

Output:
    outputs/<RUN_NAME>/csv/
        all_cosine_stats.csv
        anova_summary.csv
        paired_diff_normality_results.csv
        anova_residual_normality_results.csv
        posthoc_results.csv

Custom functions used:
    Funcs_stats.py:
        compute_similarity_stats()
        validate_dataset()
        reshape_to_long()
        run_two_way_rm_anova()
        check_paired_diff_normality()
        check_anova_residual_normality()
        run_posthoc_tests()

Public/external functions used:
    pandas.read_csv()
    pandas.DataFrame()
    pandas.concat()
    DataFrame.to_csv()
    os.path.isfile()

Configuration:
    DATASETS and RUN_NAME are imported from config.py.
    The metric analyzed is cosine similarity (Cosine_Sim).

===============================================================================
"""

import os
import warnings
import pandas as pd
from Funcs_stats import (
    compute_similarity_stats,
    validate_dataset,
    reshape_to_long,
    run_two_way_rm_anova,
    check_paired_diff_normality,
    check_anova_residual_normality,
    run_posthoc_tests,
)
from config import DATASETS, RUN_NAME

warnings.filterwarnings("ignore")


def main():
    METRIC = "cosine"
    VALUE_NAME = "Cosine_Sim"

    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    run_dir = os.path.join(BASE_DIR, "outputs", RUN_NAME)
    csv_dir = os.path.join(run_dir, "csv")
    os.makedirs(csv_dir, exist_ok=True)

    collected = {
        f"all_{METRIC}_stats": [],
        "anova_summary": [],
        "paired_diff_normality_results": [],
        "anova_residual_normality_results": [],
        "posthoc_results": [],
    }

    for dataset_name, dataset_cfg in DATASETS.items():

        print("=" * 60)
        print(f"DATASET: {dataset_name}")
        print("=" * 60)

        sizes = dataset_cfg["sizes"]
        resolution_names = {str(s) for s in sizes}
        base_resolution = dataset_cfg["base_resolution"]

        # Exclude native resolution from inferential tests: cosine sim
        # there is always exactly 1.0 for every image (embedding vs
        # itself) — not a measured value. Fine for descriptive stats,
        # breaks ANOVA/post-hoc t-tests (zero variance).
        inferential_sizes = [s for s in sizes if s != base_resolution]

        metric_file = os.path.join(csv_dir, f"{dataset_name}_{METRIC}.csv")

        if not os.path.isfile(metric_file):
            print(f"'{dataset_name}' cosine data not found — skipping.")
            continue

        combined_df = pd.read_csv(metric_file)
        combined_df.rename(columns=lambda c: int(c) if c in resolution_names else c, inplace=True)

        # ------------------------------------
        # Descriptive statistics
        # ------------------------------------
        stats_tables = compute_similarity_stats(combined_df, sizes)
        all_stats = stats_tables["All"].copy()
        all_stats.insert(0, "Dataset", dataset_name)
        collected[f"all_{METRIC}_stats"].append(all_stats)

        # ------------------------------------
        # Cross-model inferential analysis
        # ------------------------------------
        validate_dataset(combined_df, inferential_sizes)
        long_df = reshape_to_long(combined_df, inferential_sizes, value_name=VALUE_NAME)

        anova_results = run_two_way_rm_anova(long_df, dv=VALUE_NAME, save_csv=False)
        anova_df = anova_results["anova"].copy()
        anova_df.insert(0, "Dataset", dataset_name)
        collected["anova_summary"].append(anova_df)

        normality_df = check_paired_diff_normality(long_df, value_name=VALUE_NAME, save_csv=False)
        normality_df.insert(0, "Dataset", dataset_name)
        collected["paired_diff_normality_results"].append(normality_df)

        anova_normality_df = check_anova_residual_normality(long_df, value_name=VALUE_NAME, save_csv=False)
        anova_normality_df.insert(0, "Dataset", dataset_name)
        collected["anova_residual_normality_results"].append(anova_normality_df)

        posthoc_df = run_posthoc_tests(long_df, anova_results, value_name=VALUE_NAME, save_csv=False)
        if not posthoc_df.empty:
            posthoc_df.insert(0, "Dataset", dataset_name)
        collected["posthoc_results"].append(posthoc_df)

        print("=" * 60), print(f"STATISTICAL ANALYSIS FINISHED ({dataset_name})"), print("=" * 60)

    for output_name, dfs in collected.items():
        dfs = [df for df in dfs if not df.empty]
        if not dfs:
            print(f"[NO DATA] {output_name}.csv")
            continue

        combined = pd.concat(dfs, ignore_index=True)
        output_path = os.path.join(csv_dir, f"{output_name}.csv")
        combined.to_csv(output_path, index=False)
        print(f"Saved: {output_path}")

    print("=" * 60), print("STATISTICAL ANALYSIS COMPLETE"), print("=" * 60)


if __name__ == "__main__":
    main()