"""
===============================================================================
STATISTICAL TABLE GENERATION
===============================================================================

Purpose:
    Converts the CSV results produced by the previous analysis stages into
    formatted tables for final reporting.

Input:
    outputs/<RUN_NAME>/csv/

    Contains the descriptive, inferential, retrieval, and statistical CSV
    results generated by the preceding pipeline scripts.

Workflow:
    1. Locate the run-specific CSV directory using RUN_NAME from config.py.

    2. Verify that the CSV results directory exists using the public
       os.path.isdir() function. If it does not exist, the script stops and
       instructs the user to run the previous pipeline stages.

    3. Generate all final statistical tables by passing the CSV directory and
       output table directory to the custom export_all_tables() function
       imported from Funcs_tables.py.

    4. Save the generated tables under:
       outputs/<RUN_NAME>/tables/

Output:
    outputs/<RUN_NAME>/tables/

Custom functions:
    Funcs_tables.py:
        export_all_tables()

Public/external functions:
    os.path.isdir()
    os.path.join()

Configuration:
    RUN_NAME is imported from config.py and determines which experiment run's
    CSV results are converted into tables.

===============================================================================
"""

import os
import warnings
from Funcs_tables import export_all_tables
from config import RUN_NAME

warnings.filterwarnings("ignore")


def main():
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    run_dir = os.path.join(BASE_DIR, "outputs", RUN_NAME)
    csv_dir = os.path.join(run_dir, "csv")
    table_dir = os.path.join(run_dir, "tables")

    if not os.path.isdir(csv_dir):
        print(f"'{csv_dir}' not found. Run the previous pipeline stages first.")
        return

    export_all_tables(csv_dir, table_dir)

    print("=" * 60), print("TABLE GENERATION COMPLETE"), print("=" * 60)


if __name__ == "__main__":
    main()